version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db


  app:
    build: .
    container_name: app
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/"
      # Here I instruct docker to check my localhost for ollama(because I downloaded/run it on my computer)
      OLLAMA_BASE_URL: "http://host.docker.internal:11434"

volumes:
  mongodb_data_container:
